### ISSUE TITLE
documenting how to run synk from Gulp

### ISSUE THREAD

**Issue by caraya** [doug-wade/gulp-snyk#33]
I've been getting errors when using Gulp with the examples form the README. I found out that I need to run `gulp-snyk` from the command line to make the other tasks work. Is there a way to run gulp-syk to create an auth task or to log a message to user that auth needs to be run first?

It may also help point this out in the README for people who are not familiar with snyk.

**Comment by doug-wade** [comment]
Hi @caraya!  Thanks for the report! You are correct; the gang over at Snyk made some changes that now require login.  I'll take a swing at this in the next couple of days, but of course, pull requests are always welcome :wink:
